-- Solution: MS SQL Server
SELECT CITY,
       LEN(CITY)
  FROM STATION
 ORDER BY LEN(CITY),
          CITY
 OFFSET 0 ROWS
 FETCH FIRST 1 ROWS ONLY;

SELECT CITY,
       LEN(CITY)
  FROM STATION
 ORDER BY LEN(CITY) DESC,
          CITY
 OFFSET 0 ROWS
 FETCH FIRST 1 ROWS ONLY;
-- Solution: MySQL
SELECT CITY,
       LENGTH(CITY)
  FROM STATION
 ORDER BY LENGTH(CITY),
          CITY
 LIMIT 1;

SELECT CITY,
       LENGTH(CITY)
  FROM STATION
 ORDER BY LENGTH(CITY) DESC,
          CITY
 LIMIT 1;
